### ISSUE TITLE
empty metadata POST container request fails

### ISSUE THREAD

**Issue by jkasarherou** [open-io/oio-swift#31]
Results in
```
No properties found in JSON object (HTTP 400) (STATUS 400)
```

**Comment by fvennetier** [comment]
To be more precise, the swift server currently does not handle the `No properties found in JSON object (HTTP 400) (STATUS 400)` error properly and answers a `500 Internal Error` when requested with a POST and no `X-Container-Meta-` header.

Should we accept this kind of request as a no-op, or should we answer with a proper 400?

**Comment by jkasarherou** [comment]
This should not make an error
