### ISSUE TITLE
max file size?

### ISSUE THREAD

**Issue by jkasarherou** [open-io/oio-swift#62]
it seems the proxy enforces a max file size of 5GB by default, please provide info on how to change this.

**Comment by fvennetier** [comment]
Hello. The default limits for swift are in [that file](https://github.com/openstack/swift/blob/stable/pike/swift/common/constraints.py#L29). It is possible to override them in `/etc/swift/swift.conf` (and only in that file). Here is an example:
```
[swift-constraints]
max_file_size=1048576000
max_meta_value_length=2048
```
