### ISSUE TITLE
__version__ number not updated ?

### ISSUE THREAD

**Issue by dimtion** [open-io/oio-swift#72]
In the following file : https://github.com/open-io/oio-swift/blob/master/oioswift/__init__.py the version number for oio-swift is `0.6.1` which have not been updated since October 2016. 

However the latest oio-swift version number in the [release tab](https://github.com/open-io/oio-swift/releases) and the [17.04 distribution](http://mirror.openio.io/pub/repo/openio/sds/17.04/ubuntu/xenial/) is 1.1.0. 

Is there a mismatch somewhere ?

**Comment by fvennetier** [comment]
Hello. Indeed, there was a mismatch. Thank you for reporting. I will add a script to verify tag and code version coherency.
